// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AController from "./a_controller"
application.register("a", AController)

import BodyController from "./body_controller"
application.register("body", BodyController)

import CharaAutoFillController from "./chara_auto_fill_controller"
application.register("chara-auto-fill", CharaAutoFillController)

import EraAutoFillController from "./era_auto_fill_controller"
application.register("era-auto-fill", EraAutoFillController)

import GenreAutoFillController from "./genre_auto_fill_controller"
application.register("genre-auto-fill", GenreAutoFillController)

import MemoCountController from "./memo_count_controller"
application.register("memo-count", MemoCountController)

import PasswordController from "./password_controller"
application.register("password", PasswordController)

import PlaceAutoFillController from "./place_auto_fill_controller"
application.register("place-auto-fill", PlaceAutoFillController)

import PreviewController from "./preview_controller"
application.register("preview", PreviewController)

import ThemeAutoFillController from "./theme_auto_fill_controller"
application.register("theme-auto-fill", ThemeAutoFillController)
